const countriesList = [
	{ name: 'Afghanistan', code: 'AF' },
	{ name: 'Åland Islands', code: 'AX' },
	{ name: 'Albania', code: 'AL' },
	{ name: 'Algeria', code: 'DZ' },
	{ name: 'American Samoa', code: 'AS' },
	{ name: 'AndorrA', code: 'AD' },
	{ name: 'Angola', code: 'AO' },
	{ name: 'Anguilla', code: 'AI' },
	{ name: 'Antarctica', code: 'AQ' },
	{ name: 'Antigua and Barbuda', code: 'AG' },
	{ name: 'Argentina', code: 'AR' },
	{ name: 'Armenia', code: 'AM' },
	{ name: 'Aruba', code: 'AW' },
	{ name: 'Australia', code: 'AU' },
	{ name: 'Austria', code: 'AT' },
	{ name: 'Azerbaijan', code: 'AZ' },
	{ name: 'Bahamas', code: 'BS' },
	{ name: 'Bahrain', code: 'BH' },
	{ name: 'Bangladesh', code: 'BD' },
	{ name: 'Barbados', code: 'BB' },
	{ name: 'Belarus', code: 'BY' },
	{ name: 'Belgium', code: 'BE' },
	{ name: 'Belize', code: 'BZ' },
	{ name: 'Benin', code: 'BJ' },
	{ name: 'Bermuda', code: 'BM' },
	{ name: 'Bhutan', code: 'BT' },
	{ name: 'Bolivia', code: 'BO' },
	{ name: 'Bosnia and Herzegovina', code: 'BA' },
	{ name: 'Botswana', code: 'BW' },
	{ name: 'Bouvet Island', code: 'BV' },
	{ name: 'Brazil', code: 'BR' },
	{ name: 'British Indian Ocean Territory', code: 'IO' },
	{ name: 'Brunei Darussalam', code: 'BN' },
	{ name: 'Bulgaria', code: 'BG' },
	{ name: 'Burkina Faso', code: 'BF' },
	{ name: 'Burundi', code: 'BI' },
	{ name: 'Cambodia', code: 'KH' },
	{ name: 'Cameroon', code: 'CM' },
	{ name: 'Canada', code: 'CA' },
	{ name: 'Cape Verde', code: 'CV' },
	{ name: 'Cayman Islands', code: 'KY' },
	{ name: 'Central African Republic', code: 'CF' },
	{ name: 'Chad', code: 'TD' },
	{ name: 'Chile', code: 'CL' },
	{ name: 'China', code: 'CN' },
	{ name: 'Christmas Island', code: 'CX' },
	{ name: 'Cocos (Keeling) Islands', code: 'CC' },
	{ name: 'Colombia', code: 'CO' },
	{ name: 'Comoros', code: 'KM' },
	{ name: 'Congo', code: 'CG' },
	{ name: 'Congo, The Democratic Republic of the', code: 'CD' },
	{ name: 'Cook Islands', code: 'CK' },
	{ name: 'Costa Rica', code: 'CR' },
	{ name: "Cote D'Ivoire", code: 'CI' },
	{ name: 'Croatia', code: 'HR' },
	{ name: 'Cuba', code: 'CU' },
	{ name: 'Cyprus', code: 'CY' },
	{ name: 'Czech Republic', code: 'CZ' },
	{ name: 'Denmark', code: 'DK' },
	{ name: 'Djibouti', code: 'DJ' },
	{ name: 'Dominica', code: 'DM' },
	{ name: 'Dominican Republic', code: 'DO' },
	{ name: 'Ecuador', code: 'EC' },
	{ name: 'Egypt', code: 'EG' },
	{ name: 'El Salvador', code: 'SV' },
	{ name: 'Equatorial Guinea', code: 'GQ' },
	{ name: 'Eritrea', code: 'ER' },
	{ name: 'Estonia', code: 'EE' },
	{ name: 'Ethiopia', code: 'ET' },
	{ name: 'Falkland Islands (Malvinas)', code: 'FK' },
	{ name: 'Faroe Islands', code: 'FO' },
	{ name: 'Fiji', code: 'FJ' },
	{ name: 'Finland', code: 'FI' },
	{ name: 'France', code: 'FR' },
	{ name: 'French Guiana', code: 'GF' },
	{ name: 'French Polynesia', code: 'PF' },
	{ name: 'French Southern Territories', code: 'TF' },
	{ name: 'Gabon', code: 'GA' },
	{ name: 'Gambia', code: 'GM' },
	{ name: 'Georgia', code: 'GE' },
	{ name: 'Germany', code: 'DE' },
	{ name: 'Ghana', code: 'GH' },
	{ name: 'Gibraltar', code: 'GI' },
	{ name: 'Greece', code: 'GR' },
	{ name: 'Greenland', code: 'GL' },
	{ name: 'Grenada', code: 'GD' },
	{ name: 'Guadeloupe', code: 'GP' },
	{ name: 'Guam', code: 'GU' },
	{ name: 'Guatemala', code: 'GT' },
	{ name: 'Guernsey', code: 'GG' },
	{ name: 'Guinea', code: 'GN' },
	{ name: 'Guinea-Bissau', code: 'GW' },
	{ name: 'Guyana', code: 'GY' },
	{ name: 'Haiti', code: 'HT' },
	{ name: 'Heard Island and Mcdonald Islands', code: 'HM' },
	{ name: 'Holy See (Vatican City State)', code: 'VA' },
	{ name: 'Honduras', code: 'HN' },
	{ name: 'Hong Kong', code: 'HK' },
	{ name: 'Hungary', code: 'HU' },
	{ name: 'Iceland', code: 'IS' },
	{ name: 'India', code: 'IN' },
	{ name: 'Indonesia', code: 'ID' },
	{ name: 'Iran, Islamic Republic Of', code: 'IR' },
	{ name: 'Iraq', code: 'IQ' },
	{ name: 'Ireland', code: 'IE' },
	{ name: 'Isle of Man', code: 'IM' },
	{ name: 'Israel', code: 'IL' },
	{ name: 'Italy', code: 'IT' },
	{ name: 'Jamaica', code: 'JM' },
	{ name: 'Japan', code: 'JP' },
	{ name: 'Jersey', code: 'JE' },
	{ name: 'Jordan', code: 'JO' },
	{ name: 'Kazakhstan', code: 'KZ' },
	{ name: 'Kenya', code: 'KE' },
	{ name: 'Kiribati', code: 'KI' },
	{ name: "Korea, Democratic People'S Republic of", code: 'KP' },
	{ name: 'Korea, Republic of', code: 'KR' },
	{ name: 'Kuwait', code: 'KW' },
	{ name: 'Kyrgyzstan', code: 'KG' },
	{ name: "Lao People'S Democratic Republic", code: 'LA' },
	{ name: 'Latvia', code: 'LV' },
	{ name: 'Lebanon', code: 'LB' },
	{ name: 'Lesotho', code: 'LS' },
	{ name: 'Liberia', code: 'LR' },
	{ name: 'Libyan Arab Jamahiriya', code: 'LY' },
	{ name: 'Liechtenstein', code: 'LI' },
	{ name: 'Lithuania', code: 'LT' },
	{ name: 'Luxembourg', code: 'LU' },
	{ name: 'Macao', code: 'MO' },
	{ name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
	{ name: 'Madagascar', code: 'MG' },
	{ name: 'Malawi', code: 'MW' },
	{ name: 'Malaysia', code: 'MY' },
	{ name: 'Maldives', code: 'MV' },
	{ name: 'Mali', code: 'ML' },
	{ name: 'Malta', code: 'MT' },
	{ name: 'Marshall Islands', code: 'MH' },
	{ name: 'Martinique', code: 'MQ' },
	{ name: 'Mauritania', code: 'MR' },
	{ name: 'Mauritius', code: 'MU' },
	{ name: 'Mayotte', code: 'YT' },
	{ name: 'Mexico', code: 'MX' },
	{ name: 'Micronesia, Federated States of', code: 'FM' },
	{ name: 'Moldova, Republic of', code: 'MD' },
	{ name: 'Monaco', code: 'MC' },
	{ name: 'Mongolia', code: 'MN' },
	{ name: 'Montserrat', code: 'MS' },
	{ name: 'Morocco', code: 'MA' },
	{ name: 'Mozambique', code: 'MZ' },
	{ name: 'Myanmar', code: 'MM' },
	{ name: 'Namibia', code: 'NA' },
	{ name: 'Nauru', code: 'NR' },
	{ name: 'Nepal', code: 'NP' },
	{ name: 'Netherlands', code: 'NL' },
	{ name: 'Netherlands Antilles', code: 'AN' },
	{ name: 'New Caledonia', code: 'NC' },
	{ name: 'New Zealand', code: 'NZ' },
	{ name: 'Nicaragua', code: 'NI' },
	{ name: 'Niger', code: 'NE' },
	{ name: 'Nigeria', code: 'NG' },
	{ name: 'Niue', code: 'NU' },
	{ name: 'Norfolk Island', code: 'NF' },
	{ name: 'Northern Mariana Islands', code: 'MP' },
	{ name: 'Norway', code: 'NO' },
	{ name: 'Oman', code: 'OM' },
	{ name: 'Pakistan', code: 'PK' },
	{ name: 'Palau', code: 'PW' },
	{ name: 'Palestinian Territory, Occupied', code: 'PS' },
	{ name: 'Panama', code: 'PA' },
	{ name: 'Papua New Guinea', code: 'PG' },
	{ name: 'Paraguay', code: 'PY' },
	{ name: 'Peru', code: 'PE' },
	{ name: 'Philippines', code: 'PH' },
	{ name: 'Pitcairn', code: 'PN' },
	{ name: 'Poland', code: 'PL' },
	{ name: 'Portugal', code: 'PT' },
	{ name: 'Puerto Rico', code: 'PR' },
	{ name: 'Qatar', code: 'QA' },
	{ name: 'Reunion', code: 'RE' },
	{ name: 'Romania', code: 'RO' },
	{ name: 'Russian Federation', code: 'RU' },
	{ name: 'RWANDA', code: 'RW' },
	{ name: 'Saint Helena', code: 'SH' },
	{ name: 'Saint Kitts and Nevis', code: 'KN' },
	{ name: 'Saint Lucia', code: 'LC' },
	{ name: 'Saint Pierre and Miquelon', code: 'PM' },
	{ name: 'Saint Vincent and the Grenadines', code: 'VC' },
	{ name: 'Samoa', code: 'WS' },
	{ name: 'San Marino', code: 'SM' },
	{ name: 'Sao Tome and Principe', code: 'ST' },
	{ name: 'Saudi Arabia', code: 'SA' },
	{ name: 'Senegal', code: 'SN' },
	{ name: 'Serbia and Montenegro', code: 'CS' },
	{ name: 'Seychelles', code: 'SC' },
	{ name: 'Sierra Leone', code: 'SL' },
	{ name: 'Singapore', code: 'SG' },
	{ name: 'Slovakia', code: 'SK' },
	{ name: 'Slovenia', code: 'SI' },
	{ name: 'Solomon Islands', code: 'SB' },
	{ name: 'Somalia', code: 'SO' },
	{ name: 'South Africa', code: 'ZA' },
	{ name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
	{ name: 'Spain', code: 'ES' },
	{ name: 'Sri Lanka', code: 'LK' },
	{ name: 'Sudan', code: 'SD' },
	{ name: 'Suriname', code: 'SR' },
	{ name: 'Svalbard and Jan Mayen', code: 'SJ' },
	{ name: 'Swaziland', code: 'SZ' },
	{ name: 'Sweden', code: 'SE' },
	{ name: 'Switzerland', code: 'CH' },
	{ name: 'Syrian Arab Republic', code: 'SY' },
	{ name: 'Taiwan, Province of China', code: 'TW' },
	{ name: 'Tajikistan', code: 'TJ' },
	{ name: 'Tanzania, United Republic of', code: 'TZ' },
	{ name: 'Thailand', code: 'TH' },
	{ name: 'Timor-Leste', code: 'TL' },
	{ name: 'Togo', code: 'TG' },
	{ name: 'Tokelau', code: 'TK' },
	{ name: 'Tonga', code: 'TO' },
	{ name: 'Trinidad and Tobago', code: 'TT' },
	{ name: 'Tunisia', code: 'TN' },
	{ name: 'Turkey', code: 'TR' },
	{ name: 'Turkmenistan', code: 'TM' },
	{ name: 'Turks and Caicos Islands', code: 'TC' },
	{ name: 'Tuvalu', code: 'TV' },
	{ name: 'Uganda', code: 'UG' },
	{ name: 'Ukraine', code: 'UA' },
	{ name: 'United Arab Emirates', code: 'AE' },
	{ name: 'United Kingdom', code: 'GB' },
	{ name: 'United States', code: 'US' },
	{ name: 'United States Minor Outlying Islands', code: 'UM' },
	{ name: 'Uruguay', code: 'UY' },
	{ name: 'Uzbekistan', code: 'UZ' },
	{ name: 'Vanuatu', code: 'VU' },
	{ name: 'Venezuela', code: 'VE' },
	{ name: 'Viet Nam', code: 'VN' },
	{ name: 'Virgin Islands, British', code: 'VG' },
	{ name: 'Virgin Islands, U.S.', code: 'VI' },
	{ name: 'Wallis and Futuna', code: 'WF' },
	{ name: 'Western Sahara', code: 'EH' },
	{ name: 'Yemen', code: 'YE' },
	{ name: 'Zambia', code: 'ZM' },
	{ name: 'Zimbabwe', code: 'ZW' },
];
const classList = [
	{ name: 'Chemicals for use in industry', code: '1' },
	{ name: 'Paints, dyes and inks', code: '2' },
	{ name: 'Cleaning preparations and cosmetics', code: '3' },
	{ name: 'Lubricants, fuels and candles', code: '4' },
	{ name: 'Pharmaceuticals, medical and veterinary preparations', code: '5' },
	{ name: 'Common metals and their alloys; metallic building materials', code: '6' },
	{ name: 'Machines for treatment of materials and for manufacturing', code: '7' },
	{ name: 'Hand tools, cutlery and sidearms', code: '8' },
	{ name: 'Scientific, audio, visual, telecommunication and computer equipment', code: '9' },
	{ name: 'Medical and veterinary equipment', code: '10' },
	{ name: 'Lighting, heating and sanitary apparatus', code: '11' },
	{ name: 'Vehicles', code: '12' },
	{ name: 'Firearms, explosives and fireworks', code: '13' },
	{ name: 'Jewellery and watches', code: '14' },
	{ name: 'Musical instruments', code: '15' },
	{ name: 'Printed matter and stationery', code: '16' },
	{ name: 'Plastics in extruded form for use in manufacture; insulating materials', code: '17' },
	{ name: 'Leather and imitations of leather; luggage, umbrellas, walking sticks and saddlery', code: '18' },
	{ name: 'Non-metallic building materials', code: '19' },
	{ name: 'Furniture and furnishings', code: '20' },
	{ name: 'Household utensils; glassware, porcelain and earthenware', code: '21' },
	{ name: 'Ropes, string, tents, tarpaulins and sails', code: '22' },
	{ name: 'Yarns and threads', code: '23' },
	{ name: 'Textiles and household linen', code: '24' },
	{ name: 'Clothing, footwear, headgear', code: '25' },
	{ name: 'Lace and embroidery, fastenings and hair decorations', code: '26' },
	{ name: 'Carpets and other materials for covering existing floors', code: '27' },
	{ name: 'Toys, playthings, sporting articles and video game apparatus', code: '28' },
	{ name: 'Foodstuffs (meat, fish, fruit, vegetables, eggs and dairy products)', code: '29' },
	{ name: 'Foodstuffs (coffee, tea, flour, bread, sugar and confectionery)', code: '30' },
	{ name: 'Raw agricultural, horticultural and forestry products, live animals and fresh fruit and  ', code: '31' },
	{ name: 'Beers and non-alcoholic drinks', code: '32' },
	{ name: 'Alcoholic drinks (except beers)', code: '33' },
	{ name: "Tobacco, smokers' articles and electronic cigarettes", code: '34' },
	{ name: 'Advertising, business management and retail services', code: '35' },
	{ name: 'Financial and real estate services', code: '36' },
	{ name: 'Building construction, repair and installation services', code: '37' },
	{ name: 'Telecommunications services', code: '38' },
	{ name: 'Transportation and storage services', code: '39' },
	{ name: 'Material treatment services', code: '40' },
	{ name: 'Education, entertainment, sporting and cultural activities', code: '41' },
	{ name: 'Scientific, technological and design services', code: '42' },
	{ name: 'Restaurant and accommodation services', code: '43' },
	{ name: 'Medical, veterinary, beauty care and gardening services', code: '44' },
	{ name: 'Personal, security and legal services', code: '45' },
];
const patentNumbers = [
	{ name: '1', code: '1' },
	{ name: '2', code: '2' },
	{ name: '3', code: '3' },
	{ name: '4', code: '4' },
	{ name: '5', code: '5' },
	{ name: '6', code: '6' },
	{ name: '7', code: '7' },
	{ name: '8', code: '8' },
	{ name: '9', code: '9' },
	{ name: '10', code: '10' },
	{ name: '11', code: '11' },
	{ name: '12', code: '12' },
	{ name: '13', code: '13' },
	{ name: '14', code: '14' },
	{ name: '15', code: '15' },
	{ name: '16', code: '16' },
	{ name: '17', code: '17' },
	{ name: '18', code: '18' },
	{ name: '19', code: '19' },
	{ name: '20', code: '20' },
	{ name: '21', code: '21' },
	{ name: '22', code: '22' },
	{ name: '23', code: '23' },
	{ name: '24', code: '24' },
	{ name: '25', code: '25' },
	{ name: '26', code: '26' },
	{ name: '27', code: '27' },
	{ name: '28', code: '28' },
	{ name: '29', code: '29' },
	{ name: '30', code: '30' },
	{ name: '31', code: '31' },
	{ name: '32', code: '32' },
	{ name: '33', code: '33' },
	{ name: '34', code: '34' },
	{ name: '35', code: '35' },
	{ name: '36', code: '36' },
	{ name: '37', code: '37' },
	{ name: '38', code: '38' },
	{ name: '39', code: '39' },
	{ name: '40', code: '40' },
	{ name: '41', code: '41' },
	{ name: '42', code: '42' },
	{ name: '43', code: '43' },
	{ name: '44', code: '44' },
	{ name: '45', code: '45' },
	{ name: '46', code: '46' },
	{ name: '47', code: '47' },
	{ name: '48', code: '48' },
	{ name: '49', code: '49' },
	{ name: '50', code: '50' },
];

const countriesOptions = [];
const classListOptions = [];
const patentNumbersListOptions = [];

function formatOptions(arrData, arrOutput) {
	arrData.forEach((item) => {
		arrOutput.push({
			label: `${item.code} - ${item.name}`,
			value: `${item.code} - ${item.name}`,
		});
	});
}
function formatNumbers(arrData, arrOutput) {
	arrData.forEach((item) => {
		arrOutput.push({
			label: `${item.name}`,
			value: `${item.name}`,
		});
	});
}
formatOptions(countriesList, countriesOptions);
formatOptions(classList, classListOptions);
formatNumbers(patentNumbers, patentNumbersListOptions);

export { countriesOptions, classListOptions, patentNumbersListOptions };
